export default {
  apiBaseURL: 'https://api.kotori.love/',
  sourceURL: 'https://api.kotori.love/pixiv/source.php',
  authURL: 'https://api.kotori.love/pixiv/auth.php',
  favouriteURL: 'https://api.kotori.love/pixiv/favourite.php',
  baseURL: 'https://pixiv.moe/',
  trackingID: 'UA-70944432-2',
  piwikDomain: 'analytics.kotori.love',
  piwikSiteId: 1,
  projectLink: 'https://git.io/pixiv.moe',
  siteTitle: 'pixivの「ラブライブ」発見',
  keywords: [{
    en: 'lovelive',
    jp: 'ラブライブ'
  }, {
    en: 'honoka',
    jp: '高坂穂乃果'
  }, {
    en: 'kotori',
    jp: '南ことり'
  }, {
    en: 'umi',
    jp: '園田海未'
  }, {
    en: 'maki',
    jp: '西木野真姫'
  }, {
    en: 'rin',
    jp: '星空凛'
  }, {
    en: 'hanayo',
    jp: '小泉花陽'
  }, {
    en: 'nico',
    jp: '矢澤にこ'
  }, {
    en: 'eli',
    jp: '絢瀬絵里'
  }, {
    en: 'nozomi',
    jp: '东条希'
  }, {
    en: 'lovelive-sunshine',
    jp: 'ラブライブ!サンシャイン!!'
  }, {
    en: 'chika',
    jp: '高海千歌'
  }, {
    en: 'you',
    jp: '渡辺曜'
  }, {
    en: 'riko',
    jp: '桜内梨子'
  }, {
    en: 'yoshiko',
    jp: '津島善子'
  }, {
    en: 'hanamaru',
    jp: '国木田花丸'
  }, {
    en: 'dia',
    jp: '黒澤ダイヤ'
  }, {
    en: 'ruby',
    jp: '黒澤ルビィ'
  }, {
    en: 'mari',
    jp: '小原鞠莉'
  }, {
    en: 'kanan',
    jp: '松浦果南'
  }]
}
